// <auto-generated />
namespace Hostel1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class dong17102018 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dong17102018));
        
        string IMigrationMetadata.Id
        {
            get { return "201810170310200_dong17102018"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
